### ISSUE TITLE
I couldn't compile kyfd

### ISSUE THREAD

**Issue by bigreddeer** [neubig/kyfd#1]
Hello, Graham Neubig.

Thank you for your sharing weighted finite state transducer decoder, I am a researcher who is  interested in finite state transducer technology. 

By Googling, I found your decoder kyfd, 
When I compiled kyfd v 0.0.5 from your site http://www.phontron.com/kyfd/, with recent openfst-1.5.2,
the compiler showed the followings,

I added the option " -std=c++11" to every Makefiles, but I couldn't compile properly,
Please let me know how I can compile your code properly,
Thank you again for your knowledge sharing! 

/bin/bash ../../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I./../include -I/src/bin -std=c++11  -g -O2 -std=c++11 -MT decoder.lo -MD -MP -MF .deps/decoder.Tpo -c -o decoder.lo decoder.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I./../include -I/src/bin -std=c++11 -g -O2 -std=c++11 -MT decoder.lo -MD -MP -MF .deps/decoder.Tpo -c decoder.cc -o decoder.o
In file included from decoder.cc:24:0:
/usr/local/include/fst/compose.h: In instantiation of 'fst::ComposeFstImpl<C, F, T>::Weight fst::ComposeFstImpl<C, F, T>::ComputeFinal(fst::ComposeFstImpl<C, F, T>::StateId) [with C = fst::DefaultCacheStorefst::ArcTpl<fst::TropicalWeightTpl<float > >; F = fst::SequenceComposeFilterfst::FallbackMatcher<fst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > >, fst::FallbackMatcherfst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > > >; T = fst::GenericComposeStateTablefst::ArcTpl<fst::TropicalWeightTpl<float >, fst::IntegerFilterState<signed char>, fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::CompactHashStateTable<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::ComposeHash<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > > > >; fst::ComposeFstImpl<C, F, T>::Weight = fst::TropicalWeightTpl<float>; fst::ComposeFstImpl<C, F, T>::StateId = int]':
decoder.cc:400:1:   required from here
/usr/local/include/fst/compose.h:391:40: error: 'fst::ComposeFstImplfst::DefaultCacheStore<fst::ArcTpl<fst::TropicalWeightTpl<float > >, fst::SequenceComposeFilterfst::FallbackMatcher<fst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > >, fst::FallbackMatcherfst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > > >, fst::GenericComposeStateTablefst::ArcTpl<fst::TropicalWeightTpl<float >, fst::IntegerFilterState<signed char>, fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::CompactHashStateTable<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::ComposeHash<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > > > > >::M1' has no member named 'Final'
     Weight final1 = matcher1_->Final(s1);
...
/usr/local/include/fst/compose.h:412:51: error: 'fst::ComposeFstImplfst::DefaultCacheStore<fst::ArcTpl<fst::TropicalWeightTpl<float > >, fst::SequenceComposeFilterfst::FallbackMatcher<fst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > >, fst::FallbackMatcherfst::Matcher<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float > > > > >, fst::GenericComposeStateTablefst::ArcTpl<fst::TropicalWeightTpl<float >, fst::IntegerFilterState<signed char>, fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::CompactHashStateTable<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::ComposeHash<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > > > > >::M2' has no member named 'Priority'
         ssize_t priority2 = matcher2_->Priority(s2);
                                                   ^

**Comment by neubig** [comment]
Thanks for the report! Unfortunately I don't have time to look at this now,
but if you figure out the reason I'll be happy to have a pull request.
